### ISSUE TITLE
AccessControll и RBAC

### ISSUE THREAD

**Issue by dd3v** [vova07/yii2-rbac-module#1]
Здравствуйте. Скажите пожалуйста, можно ли с помощью этого модуля определить в контроллеры через "behaviors" какие "экшны" будут доступны пользователю у которого роль superadmin?

**Comment by vova07** [comment]
Здравствуйте!
Да можно. Просто пишите масив экшенов, и указываете в качестве доступной роли `superadmin`.
Идентично как в доках.

**Comment by dd3v** [comment]
C PhpManager и DbManager слегка запутался + некоторые статьи по RBAC в Yii2 устаревшие, а Ваш код помог разобраться, спасибо!

**Comment by vova07** [comment]
Не за что!
