### ISSUE TITLE
ошибка установки

### ISSUE THREAD

**Issue by VitalyEst** [vova07/yii2-rbac-module#2]
- Installing vova07/yii2-rbac-module (dev-master 30d6de0)
  Cloning 30d6de084d1f13b64a7212f9a2b9fe5f53aabff9
  30d6de084d1f13b64a7212f9a2b9fe5f53aabff9 is gone (history was rewritten?)
  Failed to download vova07/yii2-rbac-module from source: Failed to execute git checkout '30d6de084d1f13b64a7212f9a2b9fe5f53aabff9' && git reset --hard '30d6de084d1f13b64a7212f9a2b9fe5f53aabff9'

fatal: reference is not a tree: 30d6de084d1f13b64a7212f9a2b9fe5f53aabff9

**Comment by vova07** [comment]
Данный репозиторий был чуток заброшен. Его рабочая версия это 0.1.0, если вам нужен расширенный функционал  используйте лучше вот этот репозиторий: https://github.com/vova07/yii2-start-rbac-module

**Comment by VitalyEst** [comment]
Спасибо!
